### ISSUE TITLE
Error message in Firefox 45

### ISSUE THREAD

**Issue by sojusnik** [ajitk/omnibar#13]
After the update of Firefox to 45 an error message appears when left clicking on a search engine icon in the awesomebar, with the following content: 
> TypeError: O._prefSvc.getBoolPref is not a function

BTW, is this addon still under development?
